# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
- group: Release

steps:
- task: DotNetCoreCLI@2
  displayName: Build the project
  inputs:
    command: 'build'
    arguments: '--configuration release'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    command: 'test'
    projects: '**/Ana.ToDo.FunctionApp.UnitTests.csproj'
    arguments: '/p:CollectCoverage=true  /p:CoverletOutputFormat=cobertura  /p:CoverletOutput=$(Build.SourcesDirectory)\TestResults\Coverage\'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage Results'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'D:\a\1\s\TestResults\Coverage\coverage.cobertura.xml'
    failIfCoverageEmpty: true
        
- task: DotNetCoreCLI@2
  displayName: Publish the project
  inputs:
    command: 'publish'
    projects: '**/Ana.ToDo.FunctionApp.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- publish: '$(Build.ArtifactStagingDirectory)'
  artifact: drop

- task: AzureCLI@2
  displayName: Create a Resource Group
  inputs:
    azureSubscription: 'ToDoConnection'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create -l eastus -n rg-todo-app-api'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Deploy Infrustructure from ARM Template 
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ToDoConnection'
    subscriptionId: '36d3687c-f042-4575-a046-b95c67efc8ca'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-todo-app-api'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'ARM Templates/arm_rg.json'
    csmParametersFile: 'ARM Templates/armparameters.json'
    overrideParameters: '-myConnectionString "$(MyConnectionString)"'
    deploymentMode: 'Incremental'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'ToDoConnection'
    appType: 'functionApp'
    appName: 'toDoFunctionAppAna'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
    
- task: SqlAzureDacpacDeployment@1
  displayName: Deploy DB schema
  inputs:
    azureSubscription: 'ToDoConnection'
    AuthenticationType: 'server'
    ServerName: 'todoappservernew.database.windows.net'
    DatabaseName: 'todobd'
    SqlUsername: 'ana'
    SqlPassword: '007Pus007'
    deployType: 'SqlTask'
    SqlFile: 'src/Ana.ToDo.Database/toDoObjectsDB.sql'
    IpDetectionMethod: 'AutoDetect'
