# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.0.x'
    packageType: runtime
    
- task: DotNetCoreCLI@2
  displayName: Build the project
  inputs:
    command: 'build'
    arguments: '--configuration release'
    projects: 'test_api.csproj'

- task: DotNetCoreCLI@2
  displayName: Publish the project
  inputs:
    command: 'publish'
    projects: 'test_api.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- publish: '$(Build.ArtifactStagingDirectory)'
  artifact: drop

- task: AzureCLI@2
  inputs:
    azureSubscription: 'ToDoConnection'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create --name "rg-todo-app-api" --location "East US 2"'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ToDoConnection'
    subscriptionId: '36d3687c-f042-4575-a046-b95c67efc8ca'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-todo-api'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'arm_rg.json'
    csmParametersFile: 'arm_template_parameters.json'
    deploymentMode: 'Incremental'

- task: AzureFunctionApp@1
  displayName: Deploy Azure Function
  inputs:
    azureSubscription: 'ToDoConnection'
    appType: 'functionAppLinux'
    appName: 'todofunctionapplication'
    package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'



