# File: pipelines/deploymentTemplate.yml
parameters:
- name: Env
  type: string

steps:
- task: AzureCLI@2
  displayName: Create a Resource Group
  inputs:
    azureSubscription: 'ToDoConnection'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create -l eastus -n ${{parameters.Env}}-todo-app-api-rg'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Deploy Infrustructure from ARM Template 
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ToDoConnection'
    subscriptionId: '36d3687c-f042-4575-a046-b95c67efc8ca'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '${{parameters.Env}}-todo-app-api-rg'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'ARM Templates/arm_rg.json'
    csmParametersFile: 'ARM Templates/armparameters.json'
    overrideParameters: '-myConnectionString "$(MyConnectionString)" -resourceGroupName "${{parameters.Env}}-todo-app-api-rg" -subscriptionId "$(SubscriptionId)" -administratorLogin "$(AdministratorLogin)" -administratorLoginPassword "$(AdministratorPassword)"'
    deploymentMode: 'Incremental'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'ToDoConnection'
    appType: 'functionApp'
    appName: 'toDoFunctionAppAna'
    package: '$(ReleaseArtifactDirectory)/Ana.ToDo.FunctionApp.zip'
    deploymentMethod: 'auto'
        
- task: SqlAzureDacpacDeployment@1
  displayName: Deploy DB schema
  inputs:
    azureSubscription: 'ToDoConnection'
    AuthenticationType: 'server'
    ServerName: 'todoappservernew.database.windows.net'
    DatabaseName: 'todobd'
    SqlUsername: 'ana'
    SqlPassword: '007Pus007'
    deployType: 'SqlTask'
    SqlFile: 'src/Ana.ToDo.Database/toDoObjectsDB.sql'
    IpDetectionMethod: 'AutoDetect'