# File: pipelines/deploymentTemplate.yml
parameters:
- name: Env
  type: string

steps:
- task: AzureCLI@2
  displayName: Create a Resource Group
  inputs:
    azureSubscription: 'ToDoConnection'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create -l eastus -n rg-todoapp-${{parameters.Env}}'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Deploy Infrustructure from ARM Template 
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ToDoConnection'
    subscriptionId: '36d3687c-f042-4575-a046-b95c67efc8ca'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-todoapp-${{parameters.Env}}'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(ReleaseArtifactDirectory)/arm_rg.json'
    csmParametersFile: '$(ReleaseArtifactDirectory)/armparameters.json'
    overrideParameters: '-myConnectionString "$(MyConnectionString)" -resourceGroupName "rg-todoapp-${{parameters.Env}}" -subscriptionId "$(SubscriptionId)" -administratorLogin "$(AdministratorLogin)" -administratorLoginPassword "$(AdministratorPassword)" -serverName "sql-todoapp-${{parameters.Env}}" -hostingPlanName "plan-todoapp-${{parameters.Env}}" -appInsightsName "appi-todoapp-${{parameters.Env}}" -service_ToDoAppAPIManagement_name "apim-todoapp-${{parameters.Env}}" -appName "func-todoapp-${{parameters.Env}}"'
    deploymentMode: 'Incremental'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'ToDoConnection'
    appType: 'functionApp'
    appName: 'func-todoapp-${{parameters.Env}}'
    package: '$(ReleaseArtifactDirectory)/Ana.ToDo.FunctionApp.zip'
    deploymentMethod: 'auto'
        
- task: SqlAzureDacpacDeployment@1
  displayName: Deploy DB schema
  inputs:
    azureSubscription: 'ToDoConnection'
    AuthenticationType: 'server'
    ServerName: 'sql-todoapp-${{parameters.Env}}.database.windows.net'
    DatabaseName: 'sqldb-todoapp'
    SqlUsername: '$(AdministratorLogin)'
    SqlPassword: '$(AdministratorPassword)'
    deployType: 'SqlTask'
    SqlFile: '$(ReleaseArtifactDirectory)/toDoObjectsDB.sql'
    IpDetectionMethod: 'AutoDetect'